pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "football-standings:1.0"
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }

        stage('Docker Build & Push') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE .'
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker run -d -p 8080:8080 --name football-standings-container $DOCKER_IMAGE'
                }
            }
        }
    }
}
